#!/usr/bin/env python3
"""Generate data/MANIFEST.json with inventory of all data files."""
import json
import os
import hashlib

PROJECT = r'C:\Users\Admin\Research\research-draft'
DATA_DIR = os.path.join(PROJECT, 'data')
RESULTS_DIR = os.path.join(PROJECT, 'results_rootcause')
BENCHMARK_DIR = os.path.join(PROJECT, 'benchmark')

def get_file_info(fullpath):
    size = os.path.getsize(fullpath)
    relpath = os.path.relpath(fullpath, PROJECT)
    return {
        'path': relpath.replace('\\', '/'),
        'size_bytes': size,
        'description': '',
        'schema': '',
        'source': ''
    }

manifest = {
    'manifest_version': '1.0',
    'generated': '2026-07-15T00:30:00Z',
    'generator': 'Final Audit Pipeline',
    'project': 'Scoring Bias in LLM-as-a-Judge',
    'total_files': 0,
    'files': []
}

# Data files
data_files = [
    ('data/combined_80_items.json', 'Combined evaluation items (80 items across all conditions)', 'JSON array of items with instruction, response, domain, and metadata', 'Generated from mt_bench_items.json + items_base.csv'),
    ('data/dataset.json', 'Complete dataset with all model scores', 'JSON object mapping model -> probe -> scores', 'Generated by inference pipeline'),
    ('data/mt_bench_items.json', 'MT-Bench evaluation items subset', 'JSON array of instruction-response pairs', 'Sampled from MT-Bench (Zheng et al. 2023)'),
    ('data/items_base.csv', 'Base items CSV with scores', 'CSV with columns: item_id, instruction, response, domain', 'Generated from evaluation item sampling'),
    ('data/dataset_card.md', 'Dataset card with documentation', 'Markdown dataset documentation', 'Created for dataset release'),
    ('data/data_dictionary.md', 'Complete data dictionary', 'Markdown describing all fields and schemas', 'Created for dataset release'),
    ('data/human_baseline_sheet.md', 'Human baseline scoring sheet', 'Markdown with scoring instructions and format', 'Created for human evaluation protocol'),
    ('data/README_DATASET.md', 'Dataset README', 'Markdown overview of dataset usage', 'Created for dataset release'),
]

for fname, desc, schema, source in data_files:
    fullpath = os.path.join(PROJECT, fname)
    if os.path.exists(fullpath):
        info = get_file_info(fullpath)
        info['description'] = desc
        info['schema'] = schema
        info['source'] = source
        manifest['files'].append(info)

# Results files
results_files = [
    ('results_rootcause/t4fam_results.json', 'T4 family results (14 models, 7 base+instruct pairs)', 'JSON object: model -> {rubric_order, score_id, reference_answer}', 'Kaggle T4 GPU inference pipeline'),
    ('results_rootcause/study1_results.json', 'OpenRouter study1 results (22 instruct models)', 'JSON object: model -> {rubric_order, score_id, reference_answer}', 'OpenRouter API inference'),
    ('results_rootcause/rootcause_analysis.json', 'Root cause analysis original results (6 models, 3 base+instruct pairs)', 'JSON object: model -> {model_type, rubric_order, score_id, reference_answer}', 'Original Kaggle root cause study'),
    ('results_rootcause/rootcause_results.json', 'Aggregated root cause results', 'JSON with aggregated metrics', 'Generated by rootcause analysis pipeline'),
    ('results_rootcause/study1_complete.json', 'Complete study1 results', 'JSON with per-model per-probe results', 'Generated by OpenRouter analysis'),
    ('results_rootcause/bayesian_analysis.json', 'Bayesian analysis results', 'JSON with posterior distributions and Bayes factors', 'Generated by bayesian_no_pymc.py'),
    ('results_rootcause/comprehensive_analysis.py', 'Comprehensive analysis script', 'Python script for all analyses', 'Analysis pipeline'),
    ('results_rootcause/cross_probe_analysis.json', 'Cross-probe correlation analysis', 'JSON with correlation matrix', 'Generated by cross_probe_analysis.py'),
    ('results_rootcause/deep_analysis.py', 'Deep analysis script', 'Python script', 'Analysis pipeline'),
    ('results_rootcause/depth_analysis.json', 'Depth analysis results', 'JSON with per-layer attention analysis', 'Generated by deep_analysis.py'),
    ('results_rootcause/depth_findings.json', 'Depth findings summary', 'JSON with key findings', 'Generated by depth analysis'),
    ('results_rootcause/domain_analysis.py', 'Domain analysis script', 'Python script', 'Analysis pipeline'),
    ('results_rootcause/full_metrics.json', 'Full metrics across all models', 'JSON with comprehensive metrics', 'Generated by comprehensive analysis'),
    ('results_rootcause/model_ranking_analysis.json', 'Model ranking analysis', 'JSON with model rankings', 'Generated by model_ranking_analysis.py'),
    ('results_rootcause/peer_review_defense.json', 'Peer review defense notes', 'JSON with rebuttal points', 'Generated for review process'),
    ('results_rootcause/quantified_limitations.json', 'Quantified limitations', 'JSON with limitation assessments', 'Generated by limitation analysis'),
    ('results_rootcause/quick_analysis.json', 'Quick analysis summary', 'JSON with summary stats', 'Generated by quick analysis'),
    ('results_rootcause/variance_decomposition.json', 'Variance decomposition results', 'JSON with variance components', 'Generated by variance_decomposition.py'),
]

for fname, desc, schema, source in results_files:
    fullpath = os.path.join(PROJECT, fname)
    if os.path.exists(fullpath):
        info = get_file_info(fullpath)
        info['description'] = desc
        info['schema'] = schema
        info['source'] = source
        manifest['files'].append(info)

# Analysis output files
analysis_dir = os.path.join(RESULTS_DIR, 'analysis_output')
if os.path.exists(analysis_dir):
    analysis_outputs = [
        'analysis_summary.md', 'bayesian_results.json', 'bootstrapped_cis.json',
        'cohens_d.json', 'consensus_analysis.json', 'domain_analysis.json',
        'family_profiles.json', 'finding_stability.json', 'hierarchical_bayesian.json',
        'item_analysis.json', 'model_ranking.json', 'multilingual_bias.json',
        'outlier_analysis.json', 'per_item_analysis.json', 'power_analysis.json',
        'power_curve.json', 'probe_correlations.json', 'robustness_metrics.json',
        'score_distributions.json', 'score_inflation.json', 'size_correlation.json',
        'size_quantile_analysis.json', 'synthetic_validation.json',
        't4fam_deltas.json', 'training_method_analysis.json',
        'variance_decomposition.json', 'wilcoxon_results.json'
    ]
    for fname in analysis_outputs:
        fullpath = os.path.join(analysis_dir, fname)
        if os.path.exists(fullpath):
            info = get_file_info(fullpath)
            info['description'] = f'Analysis output: {fname.replace("_", " ").replace(".json", "").replace(".md", "")}'
            info['schema'] = 'JSON with analysis results'
            info['source'] = 'Analysis pipeline (comprehensive_analysis.py, etc.)'
            manifest['files'].append(info)

# Validation files
validation_dir = os.path.join(RESULTS_DIR, 'validation')
if os.path.exists(validation_dir):
    val_files = [f for f in os.listdir(validation_dir) if f.endswith(('.json', '.md', '.py'))]
    for fname in val_files:
        fullpath = os.path.join(validation_dir, fname)
        if os.path.exists(fullpath) and os.path.isfile(fullpath):
            info = get_file_info(fullpath)
            info['description'] = f'Validation output: {fname.replace("_", " ").replace(".json", "").replace(".py", "").replace(".md", "")}'
            info['schema'] = 'JSON/Markdown validation report'
            info['source'] = 'Validation pipeline (run_all_validation.py)'
            manifest['files'].append(info)

# Benchmark files
benchmark_dir = os.path.join(PROJECT, 'benchmark')
if os.path.exists(benchmark_dir):
    bench_files = [f for f in os.listdir(benchmark_dir) if f.endswith(('.json', '.csv'))]
    for fname in bench_files:
        fullpath = os.path.join(benchmark_dir, fname)
        if os.path.exists(fullpath) and os.path.isfile(fullpath):
            info = get_file_info(fullpath)
            info['description'] = f'Benchmark data: {fname}'
            info['schema'] = 'JSON/CSV benchmark results'
            info['source'] = 'Bias mitigation benchmark'
            manifest['files'].append(info)

# Synthetic data
synthetic_data = [
    ('data/synthetic/bias_interaction_synthetic.csv', 'Synthetic bias interaction data', 'CSV with simulated bias patterns', 'Generated by generate_synthetic_pilot.py'),
    ('data/synthetic/rootcause_synthetic.csv', 'Synthetic root cause data', 'CSV with simulated root cause patterns', 'Generated by rootcause synthetic generator'),
]

for fname, desc, schema, source in synthetic_data:
    fullpath = os.path.join(PROJECT, fname)
    if os.path.exists(fullpath):
        info = get_file_info(fullpath)
        info['description'] = desc
        info['schema'] = schema
        info['source'] = source
        manifest['files'].append(info)

# Multilingual items
multilingual_dir = os.path.join(PROJECT, 'data', 'multilingual')
if os.path.exists(multilingual_dir):
    for fname in os.listdir(multilingual_dir):
        fullpath = os.path.join(multilingual_dir, fname)
        if os.path.isfile(fullpath):
            info = get_file_info(fullpath)
            lang = fname.replace('items_', '').replace('.json', '')
            info['description'] = f'Multilingual items ({lang})'
            info['schema'] = f'JSON array of items in {lang}'
            info['source'] = 'Generated by generate_multilingual.py'
            manifest['files'].append(info)

# Raw data
raw_dir = os.path.join(PROJECT, 'data', 'raw')
if os.path.exists(raw_dir):
    for fname in os.listdir(raw_dir):
        fullpath = os.path.join(raw_dir, fname)
        if os.path.isfile(fullpath):
            info = get_file_info(fullpath)
            info['description'] = f'Raw data: {fname}'
            info['schema'] = 'CSV raw data'
            info['source'] = 'Experiment data collection'
            manifest['files'].append(info)

manifest['total_files'] = len(manifest['files'])

# Sort by path
manifest['files'].sort(key=lambda x: x['path'])

# Write manifest
manifest_path = os.path.join(PROJECT, 'data', 'MANIFEST.json')
with open(manifest_path, 'w') as f:
    json.dump(manifest, f, indent=2)

print(f"Written {manifest['total_files']} file entries to data/MANIFEST.json")
