"""Does every analysis get rerun by every runner that claims to rerun them all?

Three places enumerate the analyses: the CI workflow, run_all.sh (the paper's
promised one-command reproduction), and verify_like_ci.py (the local stand-in
for CI). All three are hand-written lists, and a hand-written list of things to
verify is how results_14b_analysis.json came to be committed, cited by the
paper, and compared against nothing for the length of this project.

That gap was closed for the CI diff step by deriving the expected files from
disk. This closes it for the runners: a new analyze_*.py must appear in all
three, or one of them silently stops covering the release while continuing to
report success.

The three are checked separately rather than against each other, because
agreeing with each other is exactly what they did when all three were missing
the same script.
"""

import re
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
REPRO = REPO / "paper" / "honest" / "repro"

RUNNERS = {
    "run_all.sh": REPO / "run_all.sh",
    "verify_like_ci.py": REPO / "verify_like_ci.py",
    ".github/workflows/repro.yml": REPO / ".github" / "workflows" / "repro.yml",
}


def _analyzers():
    found = {path.name for path in REPRO.glob("analyze_*.py")}
    if not found:
        pytest.skip("[repro] no analysis scripts present")
    return found


@pytest.mark.parametrize("runner", sorted(RUNNERS))
def test_the_runner_reruns_every_analysis(runner):
    path = RUNNERS[runner]
    if not path.exists():
        pytest.skip(f"[{runner}] not present")
    text = path.read_text(encoding="utf-8", errors="replace")
    named = set(re.findall(r"(analyze_[\w]+\.py)", text))

    analyzers = _analyzers()
    missing = sorted(analyzers - named)
    assert not missing, (
        f"{runner} does not rerun {missing}. Their outputs are committed and "
        f"cited, so leaving them out means the release contains numbers this "
        f"runner never regenerates."
    )

    stale = sorted(named - analyzers)
    assert not stale, (
        f"{runner} runs {stale}, which no longer exist -- the runner would fail "
        f"partway through, or silently skip depending on the shell"
    )


def test_the_newprobes_analyzer_is_run_on_every_raw_file_it_reduces():
    """It takes its input as an argument, so listing it once proves nothing.

    Each raw file it reduces has a committed *_analysis.json beside it, and
    each needs its own invocation. The 14B run was the one originally missed.
    """
    outputs = {
        path.name.replace("_analysis.json", ".json")
        for path in REPRO.glob("*_analysis.json")
    }
    raw_reduced = {name for name in outputs if (REPRO / name).exists()}
    if not raw_reduced:
        pytest.skip("[repro] no newprobes-style outputs")

    for runner in ("run_all.sh", "verify_like_ci.py"):
        path = RUNNERS[runner]
        if not path.exists():
            continue
        body = path.read_text(encoding="utf-8", errors="replace")
        if "analyze_newprobes" not in body:
            continue
        invoked = set(re.findall(r"results_[\w.]+\.json", body))
        missed = sorted(name for name in raw_reduced if name not in invoked)
        # Only the files analyze_newprobes actually reduces matter here; the
        # others are handled by their own dedicated scripts.
        missed = [n for n in missed if n in {"results_probes2.json", "results_zh.json",
                                             "results_14b.json"}]
        assert not missed, (
            f"{runner} does not pass {missed} to analyze_newprobes, so those "
            f"analyses are never regenerated by it"
        )
