"""Recompute the ground-truth table from gold_results.json, in stdlib.

tab_gold carries the paper's causal claim -- that scoring bias produces real
quality-discrimination errors, and that instruction tuning does not protect
against them. It is generated by analyze_gold.py, and the only check on it was
that it matched that generator, which cannot detect the generator being wrong.

The companion file test_the_main_table_recomputes_from_raw.py exists because
that shape of check missed a defect: values rounded once for the JSON and again
for rendering, landing on the wrong digit in three published places. This table
has the same shape -- analyze_gold.py rounds to four decimals and the table
renders at two -- so it gets the same treatment: recomputed here from the raw
per-family records with nothing imported from the analysis, and compared as
rendered digits rather than as floats within a tolerance.

Four decimals to two is a much narrower window than three to two, and no cell
falls in it today. One comes close and is worth naming rather than trusting to
stay put: novice/instruct margin drop is 0.095016, two hundred-thousandths above
the boundary that decides between 0.09 and 0.10. If that value drifts down by
0.00002 the rendered digit changes, and the double-rounding note in the failure
message is what would say so.
"""

import json
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
REPRO = REPO / "paper" / "honest" / "repro"
TABLE = REPO / "paper" / "honest" / "tables" / "tab_gold.tex"

# The four data cells of each row, in the order analyze_gold.py writes them.
COLUMNS = [
    ("base", "accuracy_under_bias"),
    ("instruct", "accuracy_under_bias"),
    ("base", "margin_drop"),
    ("instruct", "margin_drop"),
]


def _gold():
    path = REPRO / "gold_results.json"
    if not path.exists():
        pytest.skip("[repro] gold_results.json not present")
    return json.loads(path.read_text(encoding="utf-8", errors="replace"))


def _table_rows(conditions):
    if not TABLE.exists():
        pytest.skip("[repro] tab_gold.tex not present")
    wanted = {cond.title(): cond for cond in conditions}
    rows = {}
    for line in TABLE.read_text(encoding="utf-8", errors="replace").splitlines():
        cells = [c.strip() for c in line.rstrip().removesuffix("\\\\").split("&")]
        if len(cells) == 5 and cells[0] in wanted:
            rows[wanted[cells[0]]] = cells[1:]
    return rows


def _expected(payload):
    """Per condition and arm: mean accuracy under bias, mean margin drop."""
    results = payload["results"]
    families = [f for f in results if "base" in results[f] and "instruct" in results[f]]
    assert families, "no families carry both arms"
    out = {}
    for cond in (c for c in payload["conditions"] if c != "control"):
        out[cond] = {}
        for arm in ("base", "instruct"):
            accuracy = [results[f][arm][cond]["accuracy"] for f in families]
            drop = [
                results[f][arm]["control"]["mean_margin"]
                - results[f][arm][cond]["mean_margin"]
                for f in families
            ]
            out[cond][arm] = {
                "accuracy_under_bias": sum(accuracy) / len(accuracy),
                "margin_drop": sum(drop) / len(drop),
            }
    return out


def test_every_gold_cell_recomputes_at_its_printed_precision():
    payload = _gold()
    want = _expected(payload)
    rows = _table_rows(want)
    assert sorted(rows) == sorted(want), (
        f"the table lists {sorted(rows)}, the data has {sorted(want)}"
    )

    wrong = []
    for cond, cells in rows.items():
        for cell, (arm, field) in zip(cells, COLUMNS):
            exact = want[cond][arm][field]
            direct = f"{exact:.2f}"
            if cell == direct:
                continue
            via_four = f"{round(exact, 4):.2f}"
            note = " (this is the double-rounded value)" if cell == via_four else ""
            wrong.append(
                f"{cond}/{arm}/{field}: table {cell!r}, recomputing from "
                f"gold_results.json gives {exact:.6f}, which is {direct!r}{note}"
            )
    assert not wrong, (
        f"the ground-truth table does not recompute from raw: {wrong}. This "
        f"table carries the causal claim, so a cell that does not follow from "
        f"the gold pairs is the claim not following from them either."
    )


def test_the_stored_summary_agrees_with_the_same_recomputation():
    """results_gold.json must hold the same values it renders from.

    The table and the JSON are written in the same function from the same
    dict, so this cannot fail on its own -- but it pins the stored file to raw
    independently, which is what a reader recomputes when they doubt the
    figure rather than the table.
    """
    payload = _gold()
    want = _expected(payload)
    path = REPRO / "results_gold.json"
    if not path.exists():
        pytest.skip("[repro] results_gold.json not present")
    stored = json.loads(path.read_text(encoding="utf-8", errors="replace"))
    degradation = stored.get("degradation")
    if not degradation:
        pytest.skip("[repro] no degradation block")

    wrong = []
    for cond, arms in want.items():
        for arm, fields in arms.items():
            for field, exact in fields.items():
                got = degradation.get(cond, {}).get(arm, {}).get(field)
                if got is None:
                    wrong.append(f"{cond}/{arm}/{field}: absent from results_gold.json")
                elif abs(got - exact) > 5e-5:
                    wrong.append(
                        f"{cond}/{arm}/{field}: stored {got}, raw gives {exact:.6f}"
                    )
    assert not wrong, f"results_gold.json disagrees with the gold pairs: {wrong}"
