r"""Pin the derived values that sit on a rounding tie to CI's output.

The committed derived JSON is a build output, and the reproduction gate
regenerates it in CI and fails on any difference. Four entries of
responsiveness_link_points land within a whisker of a rounding tie: `round(x, 4)`
where x is just either side of ...5 in the fifth decimal. Which way it rounds
depends on the last bits of x, so it differs between environments. CI computes
0.6995 where this machine computes 0.6996.

The obvious explanation was package drift -- scipy 1.18.0 against a 1.17.1 pin.
It was wrong, and worth recording as wrong: installing the pinned stack exactly
(numpy 2.4.4, scipy 1.17.1, statsmodels 0.14.6, pandas 3.0.3) still produces
0.6996 here. The difference lives below the package layer -- OS, Python build,
or the BLAS numpy links against -- and no requirements file can pin that.

It cost five consecutive red CI runs, all on commits whose actual content was
fine. The paper is unaffected: these four numbers feed a figure, and the figure
is compared by drawn content, not by these values.

Two designs were tried and rejected before this one. "Fail if this environment
differs from CI" is red on every maintainer machine forever, which is how a gate
stops being read. "Fail if a derived file is modified outside CI" blocks the
ordinary workflow of changing an analysis and regenerating. What is left is
narrow and correct: pin the known-fragile values to what CI produces, so a local
regeneration that flips them fails here instead of three commits later in CI.
"""

import json
import re
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
REPRO = REPO / "paper" / "honest" / "repro"
MECH = REPRO / "results_mechanism.json"
PINS = REPRO / "requirements-repro.txt"

# index -> value as regenerated by CI (Linux, Python 3.11, pinned stack), taken
# from the reproduction gate's own diff output.
CI_VALUES = {6: 0.6995, 18: 0.1083, 91: 0.3871, 92: 0.2231}

NUMERIC = ("numpy", "scipy", "statsmodels", "pandas")


def _resp():
    if not MECH.exists():
        pytest.skip("[derived data] results_mechanism.json not present")
    data = json.loads(MECH.read_text(encoding="utf-8", errors="replace"))
    points = data.get("responsiveness_link_points", {}).get("resp")
    if not points:
        pytest.skip("[derived data] responsiveness_link_points absent")
    return points


def test_tie_prone_values_match_what_ci_produces():
    resp = _resp()
    wrong = []
    for index, expected in CI_VALUES.items():
        if index >= len(resp):
            wrong.append(f"resp[{index}] missing (length {len(resp)})")
        elif resp[index] != expected:
            wrong.append(f"resp[{index}] = {resp[index]}, CI produces {expected}")
    assert not wrong, (
        "committed values differ from what the reproduction gate computes: "
        + "; ".join(wrong)
        + ". These sit on a rounding tie and flip between environments, so a local "
        "regeneration has overwritten CI's values. Restore them before committing, "
        "or the gate goes red on every later commit."
    )


def test_the_pinned_indices_still_point_at_the_same_quantity():
    """Vacuity guard: if the array is rebuilt, fixed indices stop meaning anything.

    A shorter or reordered array would make the check above compare unrelated
    numbers, or skip. Length is part of what is pinned.
    """
    resp = _resp()
    assert len(resp) == 130, (
        f"responsiveness_link_points has {len(resp)} entries, expected 130 "
        f"(13 families x 5 probes x 2 arms). The pinned indices no longer identify "
        f"the values they were recorded for."
    )


def test_the_numeric_stack_is_pinned_at_all():
    """Version pins do not explain this drift, but an unpinned stack is a second source."""
    if not PINS.exists():
        pytest.skip("[pins] requirements-repro.txt not present")
    text = PINS.read_text(encoding="utf-8", errors="replace")
    pinned = {
        m.group(1).lower()
        for m in re.finditer(r"^\s*([A-Za-z0-9_.-]+)\s*==\s*[0-9]", text, re.M)
    }
    missing = [name for name in ("numpy", "scipy") if name not in pinned]
    assert not missing, f"{missing} not pinned in requirements-repro.txt"
