#!/usr/bin/env python3
"""
Ground-truth analysis: does scoring bias cause REAL quality-discrimination errors,
and does instruction tuning protect against them?

Reads gold_results.json (per family, base/instruct, per condition: mean_margin =
mean[score(good) - score(bad)] with sign fixed so positive = correct, and accuracy
= fraction of gold pairs scored in the correct order). We report, per nuisance
condition, how much the discrimination margin and accuracy degrade from control,
comparing base vs instruct.

Usage: python analyze_gold.py [gold_results.json]
Output: results_gold.json (+ printed report and LaTeX table)
"""
from __future__ import annotations
import json, sys
from pathlib import Path
import numpy as np
from scipy import stats

HERE = Path(__file__).resolve().parent
SRC = Path(sys.argv[1]) if len(sys.argv) > 1 else HERE / "gold_results.json"


def main():
    d = json.loads(SRC.read_text())
    res = d["results"]
    conds = [c for c in d["conditions"] if c != "control"]
    fams = [f for f in res if "base" in res[f] and "instruct" in res[f]]

    out = {"source": SRC.name, "n_gold": d["n_gold"], "n_families": len(fams),
           "conditions": conds, "control": {}, "degradation": {}}

    # control discrimination (can the judge tell good from bad at all?)
    for kind in ("base", "instruct"):
        accs = [res[f][kind]["control"]["accuracy"] for f in fams]
        mgs = [res[f][kind]["control"]["mean_margin"] for f in fams]
        out["control"][kind] = {"mean_accuracy": round(float(np.mean(accs)), 4),
                                "mean_margin": round(float(np.mean(mgs)), 4)}

    # per-nuisance degradation from control, base vs instruct
    for cond in conds:
        row = {}
        for kind in ("base", "instruct"):
            dm = [res[f][kind]["control"]["mean_margin"] - res[f][kind][cond]["mean_margin"] for f in fams]
            da = [res[f][kind]["control"]["accuracy"] - res[f][kind][cond]["accuracy"] for f in fams]
            acc = [res[f][kind][cond]["accuracy"] for f in fams]
            row[kind] = {"margin_drop": round(float(np.mean(dm)), 4),
                         "accuracy_drop": round(float(np.mean(da)), 4),
                         "accuracy_under_bias": round(float(np.mean(acc)), 4)}
        # paired test: is instruct's margin drop smaller than base's?
        db = [res[f]["base"]["control"]["mean_margin"] - res[f]["base"][cond]["mean_margin"] for f in fams]
        di = [res[f]["instruct"]["control"]["mean_margin"] - res[f]["instruct"][cond]["mean_margin"] for f in fams]
        try:
            _, p = stats.wilcoxon(db, di); p = round(float(p), 4)
        except ValueError:
            p = None
        row["instruct_more_robust_p"] = p
        out["degradation"][cond] = row

    (HERE / "results_gold.json").write_text(json.dumps(out, indent=2) + "\n")
    _tables(out)
    _report(out)


def _report(out):
    c = out["control"]
    print(f"Source: {out['source']}  families: {out['n_families']}  gold pairs: {out['n_gold']}\n")
    print(f"Control discrimination accuracy: base={c['base']['mean_accuracy']:.2f}  "
          f"instruct={c['instruct']['mean_accuracy']:.2f}   "
          f"(margin base={c['base']['mean_margin']:.2f}, instruct={c['instruct']['mean_margin']:.2f})\n")
    print(f"{'nuisance':10s} {'base acc':>9} {'inst acc':>9} {'base mdrop':>11} {'inst mdrop':>11} {'p':>7}")
    for cond, r in out["degradation"].items():
        print(f"{cond:10s} {r['base']['accuracy_under_bias']:9.2f} {r['instruct']['accuracy_under_bias']:9.2f} "
              f"{r['base']['margin_drop']:11.3f} {r['instruct']['margin_drop']:11.3f} {str(r['instruct_more_robust_p']):>7}")


def _tables(out):
    tdir = HERE.parent / "tables"; tdir.mkdir(parents=True, exist_ok=True)
    L = [r"% AUTO-GENERATED by analyze_gold.py", r"\begin{tabular}{lcccc}", r"\toprule",
         r"\multirow{2}{*}{\textbf{Nuisance}} & \multicolumn{2}{c}{\textbf{Accuracy under bias}} & "
         r"\multicolumn{2}{c}{\textbf{Margin drop}} \\",
         r" & base & instruct & base & instruct \\", r"\midrule"]
    for cond, r in out["degradation"].items():
        L.append(f"{cond.title()} & {r['base']['accuracy_under_bias']:.2f} & "
                 f"{r['instruct']['accuracy_under_bias']:.2f} & {r['base']['margin_drop']:.2f} & "
                 f"{r['instruct']['margin_drop']:.2f} \\\\")
    L += [r"\bottomrule", r"\end{tabular}"]
    (tdir / "tab_gold.tex").write_text("\n".join(L) + "\n")


if __name__ == "__main__":
    main()
